### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by mns0304** [yongbeam/AirCalendar#12]
library 추가 이후 호출하게 되면 ClassNotFoundException이 발생되고 있습니다.
아래 로그를 확인해보시면 JODA의 DateTime을 사용하고 계시는데 이녀석이 없어서 발생되고 있네요.

joda Datetime을 추가하시면 정상적으로 동작됩니다.

// app 단위의 build.gradle
dependencies {
    ...
    implementation 'net.danlew:android.joda:2.9.9.3'
}

// Application
class MyApplication: Application() {
    override fun onCreate() {
        super.onCreate()
        JodaTimeAndroid.init(this)
    }
}

발생되고 있는 에러 로그 ---------------------------------------------------------------

2019-10-24 19:25:36.634 8984-8984/com.jackson.calendarsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jackson.calendarsample, PID: 8984
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/joda/time/DateTime;
        at com.yongbeom.aircalendar.AirCalendarDatePickerActivity.init(AirCalendarDatePickerActivity.java:272)
        at com.yongbeom.aircalendar.AirCalendarDatePickerActivity.onCreate(AirCalendarDatePickerActivity.java:173)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.joda.time.DateTime" on path: DexPathList[[zip file "/data/app/com.jackson.calendarsample-2u1b3-wjltDwyHougLkABQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.jackson.calendarsample-2u1b3-wjltDwyHougLkABQ==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yongbeom.aircalendar.AirCalendarDatePickerActivity.init(AirCalendarDatePickerActivity.java:272) 
        at com.yongbeom.aircalendar.AirCalendarDatePickerActivity.onCreate(AirCalendarDatePickerActivity.java:173) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by empty-user77** [comment]
확인해볼께요
내부에서 joda time을 활용하고 있진 않아서 제거해야겠네요^^;
